spring:
  application:
    name: demo-spring-cloud-stream

---
management:
  endpoints:
    web.exposure.include: health, info, bindings

  endpoint:
    health:
      show-details: ALWAYS

  health:
    binders:
      enabled: true
